# This is a basic workflow to help you get started with Actions

name: Git-Pull-Push

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Preconditions:
  # 1. ssh-keygen -t ecdsa-sha2-nistp256 -C "git@github.com" -f xxx-github-action
  # 2. add xxx-github-action.pub to Deploy keys ( must 'Allow write access' )
  # 3. add xxx-github-action to Actions secrets

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Hello
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Set git ssh
        env:
          # use secrets xxx-github-action
          SSH_KEY: ${{ secrets.DK }}
        run: |
          mkdir -p ~/.ssh/
          echo -e "$SSH_KEY" > ~/.ssh/id_ecdsa
          cat ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          ssh -o PubkeyAuthentication=yes -o stricthostkeychecking=no -T git@github.com || echo "skip"

      - name: Edit File
        run: |
          msg="Edit Time: $(date +%s)"
          sed -i "s/<\!-- time -->.*<\!-- time end -->/<\!-- time -->$msg<\!-- time end -->/g" README.md

      - name: Git Config
        run: |
          git remote set-url origin "git@github.com:$GITHUB_REPOSITORY.git"
          # Any legal name and email
          git config --global user.email "$GITHUB_ACTOR@empty.site.qwe"
          git config --global user.name "$GITHUB_ACTOR-$GITHUB_WORKFLOW"
          git config --list

      - name: GIT Push
        run: |
          git add README.md
          git commit -m "$GITHUB_WORKFLOW-$(date +%s)";
          git push

